name: package

on:
  push:
    paths:
      - 'scripts/transformer/**'
    branches:
      - 'main'

  # Workflow run will run after another job has completed
  # so we wait for the workflow to complete then get going
  workflow_run:
    workflows:
      - 'release'
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: package
        working-directory: scripts/transformer/
        run: |
          mvn -B package --file pom.xml

      - name: upload transformer
        uses: actions/upload-artifact@v2
        with:
          name: vocab-transformer
          path: scripts/transformer/target/vocab-transformer-*.jar


  release_tag:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Get transformer
        uses: actions/download-artifact@v2
        with:
          name: vocab-transformer
          path: ./

      - name: Create Releases
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: '**/*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}

