name: release

on:
  push:
    tags:
      - "v*"

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java_version: '11'

    steps:

      - name: Checkout
        uses: actions/checkout@v2
